### PR TITLE
Migrate to aredis

### PR DESCRIPTION
**Pull request by qeternity**
First stab a migrating to aredis which is 1) still maintained 2) has sentinel and cluster support and 3) more performant (recent benchmarks).

aredis has built in connection pooling so I have removed the homegrown connection pool

I'll deploy this to our testing environment this week but I would appreciate some stress testing.

### CODE REVIEW

**Comment by carltongibson** [comment]
Thanks for this @qeternity. Just FYI I've had ≈zero bandwidth since the pandemic hit but I've nearly got the plates cleared to look at all things Channels over the next period. This is an interesting change. 👍

**Comment by qeternity** [comment]
@carltongibson Sounds great. Aside from future-proofing, the fact that we can easily add Sentinel and Cluster support is a huge win. We've had to build some separate infra for channels because we can't use it on our HA redis services. This would be a big win.

**Comment by qeternity** [comment]
Got sidetracked with other things this week. I've rolled this out to our testing environment and it passes all our tests. I'd love to benchmark performance but I don't have anything handy.

@carltongibson do you have any benchmarks/stress testing handy? I don't see any in the repo.

**Comment by carltongibson** [comment]
Hi @qeternity. If you see the nested readme there it does give some methodology, plus a link to the repo. 

Plus there also https://github.com/django/djangobench — I'm not sure how up to date that is. — If it's something you'd be keen to put effort into, there is a real need for (say) django-bench to be maintained 😀

**Comment by carltongibson** [comment]
Hi @qeternity — Just to update. I'm going to pull together a release with the latest fixes, but we need to assess this move a big more slowly, so thinking about over the summer, and after Django 3.1 is out, for which Channels needs some love first. 
Hope that makes sense. Thanks again/still for your input! 🙂

**Comment by qeternity** [comment]
Sure, makes sense. I might fork into something like channels_redis_cluster for anyone who absolutely needs Sentinel/Cluster support, and hopefully upstream it in the future.

**Comment by qeternity** [comment]
@carltongibson how are things looking to get this merged?

**Comment by carltongibson** [comment]
Hi! So I'm working on Channels update now. Then it'll be Daphne's turn. Then channels_redis again. 

If you'd like to come on as a collaborator, I'd love to have you. This change would need a major version bump and decent changenotes etc. 

Did you look at the other PRs? Anything else there you'd pick up for a major version?

**Comment by qeternity** [comment]
@carltongibson Great to hear. I'd love to help out, but as with everyone it's all time dependent. I've not had a look at other PRs but happy to set aside some time later this week to review.

**Comment by carltongibson** [comment]
OK, cool. Let me invite you. Welcome aboard! ⛵️

Beyond preparing a major version bump for this, there's not a lot to do ongoing. It's very quiet, but if you could just have your eye on it, I think that would be enough.

**Comment by carltongibson** [comment]
OK @qeternity You're invited to collaborate. @tarikki I've also invited you as a collaborator to the repo, since you've helped previously. 🙂

As I say, I don't think there's a lot to do on an ongoing basis. A release is change notes and looking at the other issues/PRs to see if there's anything worth adding. Once that's out, it's just looking at the issues as they come in, which isn't that often. 😀

Might be worth looking at recent commits on channels where we updated the CI. https://github.com/django/channels/blob/master/.github/workflows/tests.yml

I'm working on a release there, but if you need me for anything please just @carltongibson me. 
Thanks both.

**Pull request closed without merging**
