### PR TITLE
Better pubsub event loop handling

### PR DESCRIPTION
**Pull request by qeternity**
This PR changes the shard logic to operate with event loop context in situations where multiple event loops are running.

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Hey @qeternity — this has an intermittent error with a full channel. First failed on 3.7, then 3.9.

**Comment by qeternity** [comment]
> Hey @qeternity — this has an intermittent error with a full channel. First failed on 3.7, then 3.9.

These are #229 in the core layer

**Comment by acu192** [comment]
I _think_ this leads to duplicate messages if a group contains consumers in different event loops.

1. Consumer A (in event loop A) subscribes to "my group".
2. Consumer B (in event loop B) subscribes to "my group".
3. (now we have two `_do_receiving()` tasks (one per event loop) running and listening for "my group".
4. Messages arrives to "my group"
5. Both `_do_receiving()` tasks get it, both push it into the consumers' `Queue`s.
6. (now same message is pushed twice into each Queue)

Correct me if I'm wrong.

I think we need to keep a `self.channels` for each event loop, and a `self.groups` for each event loop ... to solve it.

Or create a new class (`class MultiLoopRedisPubSubChannelLayer`) that creates separate `RedisPubSubChannelLayer` objects, one per event loop. Like you are doing now, but just going one step higher so that you end up with one `RedisPubSubChannelLayer` for each event loop.

Thoughts?

**Comment by qeternity** [comment]
@acu192 yes, absolutely right...that's what I get for trying to bang out late night POCs while I had some time. I'll circle back to this next week with fresh eyes and more time.

**Comment by qeternity** [comment]
Actually - this becomes really prickly once you start allowing for loop closures...

**Pull request closed without merging**
