### PR TITLE
Deprecate Python 3.6 support, add Python 3.10

### PR DESCRIPTION
**Pull request by jalaziz**
* Deprecate Python 3.6 and remove code to support Python versions < 3.7.
* Add Python 3.10 to tox configuration.

### CODE REVIEW

**Comment by jalaziz** [comment]
@carltongibson Here you go! I can revert the `pubsub.py` change if you want to keep psuedo support for Python 3.6.

**Review by carltongibson — APPROVED** [review]
Great. Thanks! 👍

**Comment by smithdc1** [comment]
Need to update the GitHub workflow file too.

**Comment by carltongibson** [comment]
@smithdc1 How do you mean? 

https://github.com/django/channels_redis/pull/301/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR20

**Comment by smithdc1** [comment]
Ignore me. I tried to delete my comment but you are too quick! 

I got sucked in looking at the tox file. Sorry for the noise!

**Comment by carltongibson** [comment]
No problem. Thanks!

**Pull request merged**
