### PR TITLE
Trying to slove #179 (aioredis 1.3.1 dropped explicit loop requirement in API)

### PR DESCRIPTION
**Pull request by edelvalle**
Refs #179

### CODE REVIEW

**Comment by bjd183** [comment]
It looks like you need to fix the linter error by moving `import sys` into alphabetical order (after `import string`).

**Comment by edelvalle** [comment]
Nice! thanks!

**Comment by bjd183** [comment]
`aioredis` implements similar logic [here](https://github.com/aio-libs/aioredis/commit/810651e485ed8d04b7a23f221a0dcc2febd9a85b). I don't know if this is the right approach or not. The loop parameter is deprecated in Python 3.8 where it now automatically determines the appropriate loop (I think). Simply dropping the loop parameter is likely to break Python 3.6-3.7.

**Comment by bjd183** [comment]
Would it be preferred to check the version of aioredis?

**Comment by edelvalle** [comment]
I think you are right, is a combination of the version of python and `ioredis`. I have to check both.

right?

**Comment by bjd183** [comment]
@edelvalle  Perhaps `if sys.version_info >= (3, 8, 0) and aioredis.__version__ >= 1.3.1:` will be acceptable.

**Comment by edelvalle** [comment]
@bjd183 thanks for the advice, I was busy but finally managed to do as instructed by you.
btw, also made `black` tell what's the problem when it gets angry with our code :smile:

**Comment by bjd183** [comment]
@carltongibson how does this look?

**Comment by carltongibson** [comment]
Hi both, thanks for the work here. Looks good. 

Currently in a tight spot. 🦠 disrupting pretty much everything, so I've had ≈0 time to look at anything. I have a commitment to DRF on my list and then I'll have the capacity for Channels &co. 

If you have a bit of time to look over the other issues/PRs (maybe with @tarikki, who's been active) then I'm happy to take group consensus on issues and we can put out a release as first job back. (Equally, no stress if you don't have such capacity.)

**Comment by bjd183** [comment]
What is the best way to reduce to two commits? Squash usually results in a single commit, right? Can this be done with rebase? Or does it require cherry-pick? And are any of these possible now that the changes have already been committed and pushed?

**Comment by bjd183** [comment]
Also, (I've not done this before) is it possible for me to contribute to a pull request that I do not own? How would I do so? It is not obvious to me via this interface.

**Comment by bjd183** [comment]
@edelvalle you could also revert the CI change to black and limit this PR to the fix so it can be easily squashed.

**Comment by wmorrell** [comment]
@bjd183 How I would split one commit into two:

1. Checkout branch containing the commit to split: `git checkout edelvalle/master`
2. Make new branch from the original: `git checkout -b gh-179`
3. Rewind the commit, so `HEAD` is at the parent and the changes in the commit are in working copy: `git reset HEAD~`
4. Add in changes for first commit with: `git add` and/or `git add -p`
5. Do the first commit: `git commit`
6. Add in changes for second commit: `git add`
7. Do the second commit: `git commit`
8. Push
9. Beverage

**Comment by carltongibson** [comment]
Thanks @wmorrell. (Been knocked sideways by the current situation so had little time...)

**Comment by bjd183** [comment]
Alright, I gave that a try. I had to fork `edelvalle/master` since I cannot commit directly to it. I was able to rewind and reset to squash commits to just two. But I wasn't able to push without an additional merge commit since I was then behind the remote tracking branch. I created a PR on `edelvalle/master` which, once merged, I assume propagates to this PR. I'm curious to see how this works since the original set of multiple commits still exists in the history.

**Comment by edelvalle** [comment]
This is worse, now I have even more commits, let me try to undo all this

**Comment by wmorrell** [comment]
Oops, I should have mentioned that it's usually cleaner to re-submit a pull request than to alter (someone else's) existing request. I tried to go for that by adding instruction to make a new branch, but failed to take the suggestion all the way to new PR. I also should have suggested squashing before the `git reset HEAD~`, as it doesn't work very well to reset last commit when the upstream has a small handful of commits instead of one :)

@edelvalle, I will do a fork a bit later to get just the two commits requested. If you would like to give it a shot, I suggest use of a few rounds of `git rebase -i origin/master` along with the `git reset HEAD~` and `git add -p` tools. I'll keep a log of the commands I use, so hopefully it helps someone in the future.

**Comment by bjd183** [comment]
@wmorrell Thanks for the clarification.

**Comment by carltongibson** [comment]
Closing in favour of #193. Thanks all!

**Pull request closed without merging**
