### PR TITLE
Connection pooling and cancellation fixes

### PR DESCRIPTION
**Pull request by jberci**
This pull request contains everything we at @genialis had to do to make connection pooling work. The commits aren't squashed so that the commit logs are preserved; they describe the problems we stumbled upon.

The changes implement event loop-local connection pooling and introduce some cleanup hooks needed to avoid coroutine leaks and the like.

Message receiving also needed some work because of cancellation problems. We've seen locally that some environments cancel requests rather aggressively, which led to massive message loss with the old code. The reworked handling utilises Redis' concept of reliable queues.

Some of the original problems were due to bugs in the asyncio locking implementation, which were only fixed recently. At the time of this writing, the fixes are in Python 3.6.5 but haven't been backported further, so this code requires at least Python 3.6.5.

All tests pass and we also haven't seen any problems internally that could be attributed to this in a while. Please review.

### CODE REVIEW

**Comment by jberci** [comment]
The switch was needed for the reliable queue implementation: Redis only has a `BRPOPLPUSH` combined command, so everything had to be changed to pop from the right and push to the left. See 
https://redis.io/commands/rpoplpush#pattern-reliable-queue .

**Comment by andrewgodwin** [comment]
Aha! That was the key thing I was missing, thanks. That does mean that this will become a backwards-incompatible deploy technically, but honestly the worst thing it will do is reverse message priority on deploy so I'm alright with that, so I'll merge it in.

Thanks for your work on this!

**Comment by pr4n** [comment]
Does it mean that we **finally** have a persistent connection? and that https://github.com/django/channels_redis/pull/114 and https://github.com/django/channels_redis/pull/104 are not needed?

**Comment by andrewgodwin** [comment]
@jberci Have you seen the problems with this raised in https://github.com/django/channels_redis/issues/125? I'm going to have to revert this PR back out if we can't get those solved, unfortunately.

**Comment by harmv** [comment]
NB: connection pooling (https://github.com/django/channels_redis/pull/117) does not work when using async_to_sync() around group_send()

See: https://github.com/django/channels_redis/issues/223#issuecomment-1084688116

**Pull request merged**
