### PR TITLE
[3.4.x] Fix dictionary keys changed during iteration runtime error.

### LINKED ISSUE #243: RuntimeError: dictionary keys changed during iteration
Sometimes I can see the following error in the logs:

      ...
      File "/usr/local/lib/python3.8/site-packages/channels_redis/core.py", line 122, in close_loop
        for k, v in self.in_use.items():
    RuntimeError: dictionary keys changed during iteration

I don't use the latest redis_channel package, but I can see the same loop construct in current master as well:
 
https://github.com/django/channels_redis/blob/38ffdeb610ce175a01698ca267a6cccc171043c9/channels_redis/core.py#L125

        for k, v in self.in_use.items():
            if v is loop:
                self.in_use[k] = None

According to the python3 docs:

       Iterating views while adding or deleting entries in the dictionary 
       may raise a RuntimeError or fail to iterate over all entries. 

I'm happy to send a patch to set key as `None` out of for loop, although I'm a bit confused by the construct itself.

### PR DESCRIPTION
**Pull request by ngnpope**
Fixes #243
Closes #188
Closes #263
Closes #267

### CODE REVIEW

**Comment by ngnpope** [comment]
@carltongibson This wraps up three related PRs that were all looking to make use of the `in_use` map more robust.

**Review by carltongibson — APPROVED** [review]
OK, let's have it. Thanks @ngnpope! 


I shall post a release shortly.

**Comment by ngnpope** [comment]
Thanks @carltongibson 🦸🏻 

Also happy to help clear the PR backlog for you a bit!

**Comment by carltongibson** [comment]
Thanks @ngnpope 🙏

**Pull request merged**
