### PR TITLE
Document which Redis commands are used

### PR DESCRIPTION
**Pull request by vanschelven**
See #226, #290

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
OK, great, thanks. 👍

**Comment by acu192** [comment]
Sorry I'm late for reviewing this.

`RedisPubSubChannelLayer` uses:
- PUBLISH
- SUBSCRIBE
- UNSUBSCRIBE

**Comment by carltongibson** [comment]
@acu192 — Can you add in a followup?

**Comment by acu192** [comment]
@carltongibson Will do. I'll merge a new PR to fix later today.

**Pull request merged**
