### PR TITLE
test: Add python 3.12 and drop 3.7

### PR DESCRIPTION
**Pull request by marksweb**
This adds python 3.12 to the tests and drops 3.7

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
Look at that. Lovely 🎁

**Comment by smithdc1** [comment]
Should this be increased too? 

https://github.com/django/channels_redis/blob/main/setup.py#L32

**Comment by marksweb** [comment]
> Should this be increased too?
> 
> https://github.com/django/channels_redis/blob/main/setup.py#L32

Good spot David. I can update, though there are reasons why that might not want to be updated (yet).

**Comment by carltongibson** [comment]
Yes, good spot. (Likely there's a reference or two elsewhere, README say?, that a search would catch.)

**Comment by marksweb** [comment]
I'll take a look before I get going with the same for channels

**Pull request merged**
