### PR TITLE
PendingDeprecationWarning: encoding is deprecated, Use raw=False instead

### PR DESCRIPTION
**Pull request by kradem**

### CODE REVIEW

**Comment by andrewgodwin** [comment]
Do you know what version this changed in and when `raw` was introduced? We might need to update the library version requirement too.

**Comment by kradem** [comment]
Well [here](https://pypi.org/project/msgpack/#history) it was introduced for the first time in the [version 0.5.2](https://pypi.org/project/msgpack/0.5.2/).

**Comment by andrewgodwin** [comment]
Then you will need to update the dependency in `setup.py` to require at least 0.5.2 before I can merge this!

**Comment by andrewgodwin** [comment]
Cool, thanks!

**Pull request merged**
