### PR TITLE
fix: Make sure the Connection.disconnect gets called before the loop is closed

### PR DESCRIPTION
**Pull request by bellini666**
Fix https://github.com/django/channels_redis/issues/328

### CODE REVIEW

**Comment by carltongibson** [comment]
Ah,a PR good... (didn't see this before commenting on the ticket just now 🙂)

How might we test this? 🤔

**Comment by bellini666** [comment]
Hi @carltongibson ,

I tested it in a live project. Without this patch everytime I would instantiate the layer object and call `group_send` inside a django view (not a channel consumer) I would get the error I reported in the issue. That because the pool gets deleted inside the wrapped `loop.close`, which schedules `.disconnect()` to be called by the loop, but since it is being closed there it doesn't get a chance to run.

Wi that patch the error don't happen because the connection gets closed in that `redis.close()` call (which is the correct behaviour, since we don't have more than one connection in that pool. It was created specifically for that conn)

If you are looking for a unit test, I can try to write one. Don't know how to properly mock this to ensure that the coroutine was never run, but I can give it a try.

Note that this fixes the PubSub layer. The core one has a similar issue (https://github.com/django/channels_redis/issues/327), which I did not find a good solution for it. The only difference there is that the `disconnect` does get called, but it is somehow run by a different loop (probably because the [loop that created the pool](https://github.com/django/channels_redis/blob/main/channels_redis/core.py#L718) is not the same that called the [close_pools](https://github.com/django/channels_redis/blob/main/channels_redis/core.py#L492) function, but I don't know exactly why)

**Comment by bellini666** [comment]
obs. I'm running the beta versions of channels and channels_redis, and while this is not merged I monkey-patched it to force the same behaviour:

```python
_original_ensure_redis = RedisSingleShardConnection._ensure_redis


def _ensure_redis(self):
    # FIXME: This can be removed once this issue is fixed and released:
    # https://github.com/django/channels_redis/issues/328
    need_patch_redis = self._redis is None
    retval = _original_ensure_redis(self)

    if need_patch_redis:
        self._redis.close = functools.partial(
            self._redis.close,
            close_connection_pool=True,
        )

    return retval


RedisSingleShardConnection._ensure_redis = _ensure_redis
```

It is running in production in a project that relies a lot in the PubSub behaviour for 3 days now and everything is running fine! :)

**Comment by carltongibson** [comment]
Thanks for the follow up @bellini666   

As I say sounds correct. Let me have a play. 👍

**Pull request merged**
